# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

# environment variables
environment:
  matrix:
    - PYTHON: "C:\\Miniconda35-x64"
    - PYTHON: "C:\\Miniconda36-x64"
    - PYTHON: "C:\\Miniconda37-x64"

cache:
  - '%PYTHON%\pkgs'

# scripts that run after cloning repository
install:
  # Ensure python scripts are from right version:
  - 'SET "PATH=%PYTHON%\\Scripts;%PATH%"'
  # Install most deps by conda
  - 'conda config --add channels conda-forge'
  - 'conda update -y conda'
  - 'conda install -q -y hyperspy'
  # Install our package:
  - 'python -m pip install --upgrade pip'

  # Try to run twice as workaround for permission error...
  - 'pip install pypiwin32 || pip install pypiwin32'
  - 'pip install -e ".[test]"'

build: off


# to run your custom scripts instead of automatic tests
test_script:
  - '%CMD_IN_ENV% py.test -l --cov-report html --cov=hyperspyui'

after_test:
  - python setup.py bdist_wheel

artifacts:
  - path: dist\*.whl
    name: wheels

on_success:
  - '%CMD_IN_ENV% conda clean -y --tarballs'
