# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

# environment variables
environment:

  global:
    DEPS: "hyperspy-gui-traitsui qtpy pyqode.python"
    TEST_DEPS: "pytest pytest-qt pytest-cov"

  matrix:
    - PY_VERSION: 3.7
    - PY_VERSION: 3.6
    - PY_VERSION: 3.5

# scripts that run after cloning repository
install:
  # Activate miniconda root environment
  - "CALL C:\\Miniconda37-x64\\Scripts\\activate.bat"

  # Setup miniconda environment.
  - ps: Add-AppveyorMessage "Setup miniconda environment..."
  # See https://github.com/conda/conda/issues/8836 & others
  - set "PATH=%MINICONDA%\condabin:%PATH%"
  - "conda update -y -n base -c defaults conda"
  - 'conda config --add channels conda-forge'
  - "conda create -y -n testenv python=%PY_VERSION%"
  - "activate testenv"

  # Install the dependencies of hyperspyUI.
  - 'conda install -yq %DEPS% %TEST_DEPS%'

  # Install our package
  - 'pip install -e .'

build: off

# to run your custom scripts instead of automatic tests
test_script:
  - 'pytest -l --cov-report html --cov=hyperspyui'

after_test:
  - 'python setup.py bdist_wheel'

artifacts:
  - path: dist\*.whl
    name: wheel

