name: Documentation

on: [push, pull_request]

jobs:
  build_doc:
    permissions:
      contents: write
    name: Build doc
    runs-on: ubuntu-latest
    env:
      DISPLAY: :0
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: 3.8

      - name: Install
        run: |
          pip install PyQt5 PyQtWebEngine
          pip install -e .[build-doc]

      - name: Install Dependencies
        run: |
          pip install PyQt5 PyQtWebEngine
          sudo apt-get install -y xvfb libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xinput0 libxcb-xfixes0

      - name: Start xvfb
        run: |
          sudo /usr/bin/Xvfb $DISPLAY -screen 0 1280x1024x24 & 

      - name: Build doc
        run: |
          cd doc && make html

      - uses: actions/upload-artifact@v2
        with:
          path: ./doc/build/*

      - uses: peaceiris/actions-gh-pages@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doc/build/html
