name: Release
# This workflow builds the wheels "on tag".
# If run from the hyperspy/hyperspyUI repository, the wheels will be
# uploaded to pypi; otherwise, the wheels will be available as a github artifact.
# This workflow overwrite the version in `hyperspyui/version.py`
# with the tag
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  create_release:
    permissions:
      contents: write
    name: Create Release
    runs-on: ubuntu-latest
    outputs: 
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      VERSION: ${{ env.VERSION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions
        with:
          draft: false
      - name: Get version (on tag)
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV

  build_wheels_linux:
    name: Wheels on ubuntu-latest
    needs: create_release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install release dependencies
        run: |
          python -m pip install wheel

      - name: Overwrite `version.py` with tag
        if: startsWith(github.ref, 'refs/tags/')
        env: 
          version_file: hyperspyui/version.py
          VERSION: ${{ needs.create_release.outputs.VERSION }}
        run: |
          echo '__version__ = "${{ env.VERSION }}"' > ${{ env.version_file }}

      - name: Build source distribution
        run: |
          python setup.py sdist bdist_wheel

      - name: Display content dist folder
        run: |
          ls dist/

      - name: Install and test distribution
        env:
          MPLBACKEND: agg
        run: |
          pip install --find-links dist hyperspyui[tests]

      - uses: actions/upload-artifact@v2
        with:
          path: |
            ./dist/*.whl
            ./dist/*.tar.gz

      - name: Publish wheels to PyPI
        if: github.repository_owner == 'hyperspy'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          # Github secret set in the hyperspy/hyperspyui repository
          # Not available from fork or pull request
          # Secrets are not passed to workflows that are triggered by a pull request from a fork
          password: ${{ secrets.PYPI_API_TOKEN }}
