name: Tests

on: [push, pull_request]

jobs:
  run_test_site:
    name: py${{ matrix.PYTHON_VERSION }}${{ matrix.LABEL }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      HYPERSPY_DEV: false
      DISPLAY: :0
    strategy:
      fail-fast: false
      matrix:
        PYTHON_VERSION: ['3.7', '3.9', '3.10']
        include:
          - PYTHON_VERSION: '3.8'
            HYPERSPY_DEV: true

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: ${{ matrix.PYTHON_VERSION }}

      - name: Display version
        run: |
          python --version
          pip --version

      - name: 'Install Ubuntu packages for Qt'
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install qt5-default
          sudo apt-get install libxkbcommon-x11-0
          sudo apt-get install libxcb-icccm4
          sudo apt-get install libxcb-image0
          sudo apt-get install libxcb-keysyms1
          sudo apt-get install libxcb-randr0
          sudo apt-get install libxcb-render-util0
          sudo apt-get install libxcb-xinerama0

      - name: Install Dependencies
        run: |
          pip install pyqt5 PyQtWebEngine

      - name: Install
        shell: bash
        run: |
          pip install --upgrade -e .[tests]

      - name: Install HyperSpy (RELEASE_next_minor)
        shell: bash
        if: "contains( matrix.HYPERSPY_DEV, 'true')"
        run: |
          pip install https://github.com/hyperspy/hyperspy/archive/RELEASE_next_minor.zip

      - name: Run test suite
        run: |
          sudo apt-get install xvfb
          xvfb-run pytest --pyargs hyperspyui

